Repository nuagenetworks/vis-graphs, pull requests merged in 2021-01, with the labels that each got.

#438 Fix Heatmap and Area Graph legends
  Graphs/AbstractGraph.js
  Graphs/AreaGraph/index.js
  Graphs/Components/utils/Legend/StandardLegend.js
  Graphs/Components/utils/Legend/index.js
  Graphs/HeatmapGraph/index.js
Labels: 20.10, ready for review

#437 VSD-51249 increased legend font size - r20.10
  Graphs/style.css
Labels: ready for review

#441 Table - disable scroll-sort on specific columns
  Graphs/Table/index.js
Labels: 21.x, ready for review

#442 VSD-51747 onClick error when clicked inside graph area
  Graphs/ChordGraph/Svg.js
Labels: ready for review

#443 VSD-51734 - tree view pagination
  Graphs/TreeGraph/index.js
Labels: 21.x, ready for review

#444 [20.10] cherry-picked 0.0 commit and resolved conflicts
  Graphs/TreeGraph/index.js
Labels: 20.10, ready for review

#445 VSD-51747 onClick error when clicked inside graph area (r20.10)
  Graphs/ChordGraph/Svg.js
Labels: 20.10, ready for review
